language: node_js
node_js:
  - "7"
cache:
  directories:
    - $(npm config get prefix)/bin/typescript
    - $(npm config get prefix)/bin/tslint
    - $(npm config get prefix)/bin/tslint-config-standard
before_install:
  - npm list -g typescript || npm install -g typescript
  - npm list -g tslint || npm install -g tslint
  - npm list -g tslint-config-standard || npm install -g tslint-config-standard
script:
  - tslint --type-check --project .
  - tsc
before_deploy:
  - rm -rf .gitignore scripts/ *.json .travis.yml README.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
