language: node_js
node_js:
  - "7"
before_install:
  - npm install -g typescript
  - npm install -g tslint tslint-config-standard
script:
  - tslint
  - tsc
before_deploy:
  - rm .gitignore
  - rm *.ts
  - rm *.json
  - rm .travis.yml
  - rm README.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master