language: node_js
node_js:
  - "7"
cache:
  directories:
    - $(npm config get prefix)/bin/typescript
    - $(npm config get prefix)/bin/tsc
    - $(npm config get prefix)/bin/tslint
    - $(npm config get prefix)/bin/tslint-config-standard
    - $(npm config get prefix)/lib/node_modules
before_install:
  - npm list -g typescript@2.5.3 --depth=0 || npm install -g typescript@2.5.3
  - npm list -g tslint@5.8.0 --depth=0 || npm install -g tslint@5.8.0
  - npm list -g tslint-config-standard@6.0.1 --depth=0 || npm install -g tslint-config-standard@6.0.1
script:
  - tslint --type-check --project .
  - tsc
before_deploy:
  - rm -rf .gitignore scripts/ *.json .travis.yml README.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
