language: node_js
node_js:
  - "7"
before_install:
  - npm install -g typescript tslint tslint-config-standard
script:
  - tslint --type-check --project .
  - tsc
before_deploy:
  - rm -rf .gitignore scripts/ *.json .travis.yml README.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
